{{- if .Values.collector.serviceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.collector.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
{{- end }}