apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelbrot-collector-role
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelbrot-collector-binding
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.collector.serviceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: otelbrot-collector-role
  apiGroup: rbac.authorization.k8s.io