apiVersion: v1
kind: Service
metadata:
  name: otel-gateway-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: otel-gateway-collector
    {{- include "otelbrot-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/instance: otel-gateway-collector
    app.kubernetes.io/name: otel-gateway-collector