apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelbrot-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
spec:
  mode: {{ .Values.collector.mode | default "deployment" }}
  replicas: {{ .Values.collector.replicas | default 2 }}
  serviceAccount: {{ .Values.collector.serviceAccount | default "otelbrot-collector" }}
  image: {{ .Values.collector.image.repository | default "otel/opentelemetry-collector-contrib" }}:{{ .Values.collector.image.tag | default "0.121.0" }}
  resources:
    limits:
      cpu: {{ .Values.collector.resources.limits.cpu | default "500m" }}
      memory: {{ .Values.collector.resources.limits.memory | default "1Gi" }}
    requests:
      cpu: {{ .Values.collector.resources.requests.cpu | default "100m" }}
      memory: {{ .Values.collector.resources.requests.memory | default "200Mi" }}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: {{ .Values.collector.config.receivers.otlp.protocols.grpc.endpoint | default "0.0.0.0:4317" }}
          http:
            endpoint: {{ .Values.collector.config.receivers.otlp.protocols.http.endpoint | default "0.0.0.0:4318" }}

    processors:
      memory_limiter:
        check_interval: {{ .Values.collector.config.processors.memory_limiter.check_interval | default "1s" }}
        limit_percentage: {{ .Values.collector.config.processors.memory_limiter.limit_percentage | default 75 }}
        spike_limit_percentage: {{ .Values.collector.config.processors.memory_limiter.spike_limit_percentage | default 15 }}
      batch:
        send_batch_size: {{ .Values.collector.config.processors.batch.send_batch_size | default 10000 }}
        timeout: {{ .Values.collector.config.processors.batch.timeout | default "10s" }}
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
      resource:
        attributes:
          - key: service.name
            value: "otelbrot-collector"
            action: insert
          - key: k8s.cluster.name
            value: {{ .Values.collector.config.processors.resource.attributes.cluster_name | default "otelbrot" }}
            action: upsert

    exporters:
      debug: 
        verbosity: {{ .Values.collector.config.exporters.debug.verbosity | default "normal" }}
      otlp/gateway:
        endpoint: {{ .Values.collector.config.exporters.otlp_gateway.endpoint | default "otel-gateway-collector-agent.otelbrot.svc.cluster.local:4317" }}
        tls:
          insecure: {{ .Values.collector.config.exporters.otlp_gateway.tls.insecure | default true }}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [debug, otlp/gateway]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [debug, otlp/gateway]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [debug, otlp/gateway]