apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-otel-lgtm-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.otelLgtm.persistence.size | default "10Gi" }}
  {{- if .Values.otelLgtm.persistence.storageClass }}
  storageClassName: {{ .Values.otelLgtm.persistence.storageClass }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otel-lgtm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
    app: otel-lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otelbrot-app.selectorLabels" . | nindent 6 }}
      app: otel-lgtm
  template:
    metadata:
      labels:
        {{- include "otelbrot-app.selectorLabels" . | nindent 8 }}
        app: otel-lgtm
    spec:
      volumes:
        - name: otel-lgtm-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-otel-lgtm-data
      containers:
        - name: otel-lgtm
          image: {{ .Values.otelLgtm.image.repository }}:{{ .Values.otelLgtm.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.otelLgtm.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.otelLgtm.resources | nindent 12 }}
          volumeMounts:
            - name: otel-lgtm-data
              mountPath: /var/lib/lgtm
              subPath: data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-lgtm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otelbrot-app.labels" . | nindent 4 }}
    app: otel-lgtm
spec:
  type: {{ .Values.otelLgtm.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.otelLgtm.service.ports.otelGrpc.port }}
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.otelLgtm.service.ports.otelHttp.port }}
      targetPort: 4318
      protocol: TCP
      name: otlp-http
    - port: {{ .Values.otelLgtm.service.ports.grafana.port }}
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    {{- include "otelbrot-app.selectorLabels" . | nindent 4 }}
    app: otel-lgtm