# Values for Grafana LGTM Distributed
# https://github.com/grafana/helm-charts/tree/main/charts/lgtm-distributed

nameOverride: "lgtm"
fullnameOverride: "lgtm"

gateway:
  enabled: true
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

# Minio for local storage
minio:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  persistence:
    size: 10Gi
  service:
    annotations: {}
    type: ClusterIP
    port: 9000
  # Default values that get set
  rootUser: grafana-mimir
  rootPassword: supersecret
  buckets:
    - name: tempo-traces
      policy: none
      purge: false
    - name: loki-data
      policy: none
      purge: false
    - name: mimir-data
      policy: none
      purge: false
  
# Tempo for traces
tempo:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  storage:
    trace:
      backend: local # Use local storage instead of S3 
      local:
        path: /var/tempo/traces
  tempoQuery:
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

# Loki for logs
loki:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  storage:
    type: s3
    s3:
      s3: s3://grafana-mimir:supersecret@lgtm-minio:9000/loki-data
      s3ForcePathStyle: true
      insecure: true

# Mimir for metrics
mimir:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  minio:
    service:
      annotations: {}
      port: 9000
      type: ClusterIP
  storage:
    backend: s3
    s3:
      endpoint: lgtm-minio.monitoring.svc.cluster.local:9000
      access_key_id: grafana-mimir
      secret_access_key: supersecret
      bucket_name: mimir-data
      insecure: true

# Grafana for visualization
grafana:
  enabled: true
  adminPassword: admin
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Tempo
          type: tempo
          access: proxy
          url: http://lgtm-tempo-query-frontend:3100
        - name: Loki
          type: loki
          access: proxy
          url: http://lgtm-loki-gateway:3100
        - name: Mimir
          type: prometheus
          access: proxy
          url: http://lgtm-mimir-nginx:9090
          jsonData:
            httpMethod: "GET"
  service:
    type: ClusterIP
    port: 3000