apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: otelbrot
spec:
  mode: daemonset
  serviceAccount: otel-collector
  image: otel/opentelemetry-collector-contrib:0.121.0
  env:
    - name: HONEYCOMB_API_KEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-api-key
          key: api-key
  volumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      kubeletstats:
        collection_interval: 60s
        auth_type: "serviceAccount"
        endpoint: "${K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
      filelog:
        include_file_path: true
        exclude:
          - /var/log/pods/*collector*/*collector*/*.log
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
      resource:
        attributes:
          - key: k8s.cluster.name
            value: "otelbrot"
            action: upsert

    exporters:
      debug: {}
      otlphttp/lgtm:
        endpoint: http://lgtm-gateway.monitoring.svc.cluster.local:4318
        tls:
          insecure: true
        headers:
          X-Scope-OrgID: "1"
      otlp/honeycomb:
        endpoint: api.honeycomb.io:443
        headers:
          x-honeycomb-team: ${HONEYCOMB_API_KEY}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [debug, otlphttp/lgtm, otlp/honeycomb]
        metrics:
          receivers: [otlp, kubeletstats]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [debug, otlphttp/lgtm, otlp/honeycomb]
        logs:
          receivers: [otlp, filelog]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [debug, otlphttp/lgtm, otlp/honeycomb]
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-agent
  namespace: otelbrot
spec:
  exporter:
    endpoint: http://otel-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.13.2