apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
  namespace: otelbrot
  labels:
    app: go-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-worker
  template:
    metadata:
      labels:
        app: go-worker
      annotations:
        instrumentation.opentelemetry.io/inject-java: "otelbrot/java-agent"
    spec:
      containers:
      - name: go-worker
        image: otelbrot/go-worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.otelbrot.svc.cluster.local:4317"
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator.otelbrot.svc.cluster.local:8080"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: go-worker
  namespace: otelbrot
spec:
  selector:
    app: go-worker
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP