apiVersion: batch/v1
kind: Job
metadata:
  name: go-worker-sample
  namespace: otelbrot
spec:
  template:
    spec:
      containers:
      - name: go-worker
        image: otelbrot/go-worker:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: go-worker-otel-config-volume
          mountPath: /app/config
        env:
        - name: OTEL_CONFIG_FILE
          value: "/app/config/otel-config.yaml"
        - name: OTEL_SERVICE_NAME
          value: "go-worker"
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator:8080"
        - name: JOB_ID
          value: "sample-job-001"
        - name: TILE_ID
          value: "sample-tile-001"
        - name: X_MIN
          value: "-2.0"
        - name: X_MAX
          value: "1.0"
        - name: Y_MIN
          value: "-1.5"
        - name: Y_MAX
          value: "1.5"
        - name: WIDTH
          value: "800"
        - name: HEIGHT
          value: "600"
        - name: MAX_ITERATIONS
          value: "1000"
      restartPolicy: OnFailure
      volumes:
      - name: go-worker-otel-config-volume
        configMap:
          name: go-worker-otel-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker-controller
  namespace: otelbrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-worker-controller
  template:
    metadata:
      labels:
        app: go-worker-controller
    spec:
      serviceAccountName: orchestrator-sa
      containers:
      - name: go-worker-controller
        image: otelbrot/go-worker:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: go-worker-otel-config-volume
          mountPath: /app/config
        env:
        - name: OTEL_CONFIG_FILE
          value: "/app/config/otel-config.yaml"
        - name: OTEL_SERVICE_NAME
          value: "go-worker-controller"
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator:8080"
      volumes:
      - name: go-worker-otel-config-volume
        configMap:
          name: go-worker-otel-config