apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-orchestrator-config
  namespace: otelbrot
data:
  otel-agent-config.yaml: |
    # The file format version.
    file_format: "0.3"
    
    # Configure if the SDK is disabled or not. This is not required to be provided to ensure the SDK isn't disabled, the default value when this is not provided is for the SDK to be enabled.
    disabled: false
    
    # Configure resource for all signals.
    resource:
      # Configure resource attributes.
      attributes:
        - name: service.name
          value: orchestrator
    
    # Configure general attribute limits. See also tracer_provider.limits, logger_provider.limits.
    attribute_limits:
      # Configure max attribute count.
      attribute_count_limit: 128
    
    # Configure text map context propagators.
    propagator:
      # Configure the set of propagators to include in the composite text map propagator.
      composite: [ tracecontext, baggage ]
    
    # Configure tracer provider.
    tracer_provider:
      # Configure span processors.
      processors:
        - # Configure a batch span processor.
          batch:
            # Configure delay interval (in milliseconds) between two consecutive exports.
            schedule_delay: 5000
            # Configure maximum allowed time (in milliseconds) to export data.
            export_timeout: 30000
            # Configure maximum queue size.
            max_queue_size: 2048
            # Configure maximum batch size.
            max_export_batch_size: 512
            # Configure exporter.
            exporter:
              # Configure exporter to be OTLP.
              otlp:
                # Configure protocol.
                protocol: http/protobuf
                # Configure endpoint.
                endpoint: http://otel-collector:4318/v1/traces
                # Configure compression.
                compression: gzip
                # Configure max time (in milliseconds) to wait for each export.
                timeout: 10000
                headers: []
      # Configure span limits. See also attribute_limits.
      limits:
        # Configure max attribute count. Overrides .attribute_limits.attribute_count_limit.
        attribute_count_limit: 128
        # Configure max span event count.
        event_count_limit: 128
        # Configure max span link count.
        link_count_limit: 128
        # Configure max attributes per span event.
        event_attribute_count_limit: 128
        # Configure max attributes per span link.
        link_attribute_count_limit: 128
      # Configure the sampler.
      sampler:
        # Configure sampler to be parent_based.
        parent_based:
          # Configure the parent_based sampler's root sampler to be rule_based_routing sampler.
          root:
            always_on: {}
          # Configure remote_parent_sampled sampler.
          remote_parent_sampled:
            # Configure sampler to be always_on.
            always_on: {}
          # Configure remote_parent_not_sampled sampler.
          remote_parent_not_sampled:
            # Configure sampler to be always_off.
            always_off: {}
          # Configure local_parent_sampled sampler.
          local_parent_sampled:
            # Configure sampler to be always_on.
            always_on: {}
          # Configure local_parent_not_sampled sampler.
          local_parent_not_sampled:
            # Configure sampler to be always_off.
            always_off: {}
    
    # Configure meter provider.
    meter_provider:
      # Configure metric readers.
      readers:
        - # Configure a periodic metric reader.
          periodic:
            # Configure delay interval (in milliseconds) between start of two consecutive exports.
            interval: 60000
            # Configure maximum allowed time (in milliseconds) to export data.
            timeout: 30000
            # Configure exporter.
            exporter:
              # Configure exporter to be OTLP.
              otlp:
                # Configure protocol.
                protocol: http/protobuf
                # Configure endpoint.
                endpoint: http://otel-collector:4318/v1/metrics
                # Configure compression.
                compression: gzip
                # Configure max time (in milliseconds) to wait for each export.
                timeout: 10000
                headers: []
                # Configure temporality preference.
                temporality_preference: cumulative
                # Configure default histogram aggregation.
                default_histogram_aggregation: explicit_bucket_histogram
    
    # Configure logger provider.
    logger_provider:
      # Configure log record processors.
      processors:
        - # Configure a batch log record processor.
          batch:
            # Configure delay interval (in milliseconds) between two consecutive exports.
            schedule_delay: 1000
            # Configure maximum allowed time (in milliseconds) to export data.
            export_timeout: 30000
            # Configure maximum queue size.
            max_queue_size: 2048
            # Configure maximum batch size.
            max_export_batch_size: 512
            # Configure exporter.
            exporter:
              # Configure exporter to be OTLP.
              otlp:
                # Configure protocol.
                protocol: http/protobuf
                # Configure endpoint.
                endpoint: http://otel-collector:4318/v1/logs
                # Configure compression.
                compression: gzip
                # Configure max time (in milliseconds) to wait for each export.
                timeout: 10000
                headers: []
      # Configure log record limits. See also attribute_limits.
      limits:
        # Configure max attribute count. Overrides .attribute_limits.attribute_count_limit.
        attribute_count_limit: 128
    
    
    # Configure instrumentation.
    instrumentation:
      # Configure OpenTelemetry Java Agent.
      java:
        common:
          default-enabled: true
        # Configuration logback-appender instrumentation.
        java-util-logging:
          enabled: true
          experimental-log-attributes: false
        # Configuration logback-appender instrumentation.
        logback-appender:
          enabled: true
          experimental-log-attributes: false
          experimental:
            capture-code-attributes: false
            capture-marker-attributes: false
            capture-key-value-pair-attributes: false
            capture-logger-context-attributes: false
            capture-arguments: false
            capture-mdc-attributes: false