---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: otelbrot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
  namespace: otelbrot
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-rb
  namespace: otelbrot
subjects:
- kind: ServiceAccount
  name: orchestrator-sa
  namespace: otelbrot
roleRef:
  kind: Role
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
