apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: otelbrot
  labels:
    app: worker
  annotations:
    instrumentation.opentelemetry.io/inject-java: "otelbrot/java-agent"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        instrumentation.opentelemetry.io/inject-java: "otelbrot/java-agent"
    spec:
      containers:
      - name: worker
        image: otelbrot/worker:latest
        imagePullPolicy: IfNotPresent  # Use locally built image
        ports:
        - containerPort: 8081
        env:
        - name: APP_ORCHESTRATOR_URL
          value: "http://orchestrator:8080"
        - name: OTEL_SERVICE_NAME
          value: "otelbrot-worker"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 15
