apiVersion: v1
kind: ConfigMap
metadata:
  name: go-worker-otel-config
  namespace: {{ .Release.Namespace }}
data:
  otel-config.yaml: |
    # OpenTelemetry SDK configuration (v0.3.0)
    file_format: "0.3"
    disabled: false

    # Resource configuration
    resource:
      attributes:
        - name: service.name
          value: go-worker
        - name: service.version
          value: 0.1.0
        - name: k8s.cluster.name
          value: otelbrot

    # Context propagation
    propagator:
      composite: [ tracecontext, baggage ]

    # Tracer provider configuration
    tracer_provider:
      sampler:
        parent_based:
          root:
            always_on: {}

      processors:
        - simple:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otelbrot-collector.{{ .Release.Namespace }}.svc.cluster.local:4318/v1/traces
                compression: gzip
                timeout: 10000
                headers: []

      limits:
        attribute_count_limit: 128
        event_count_limit: 128
        link_count_limit: 128
        event_attribute_count_limit: 128
        link_attribute_count_limit: 128

    # Meter provider configuration
    meter_provider:
      readers:
        - periodic:
            interval: 1000
            timeout: 30000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otelbrot-collector.{{ .Release.Namespace }}.svc.cluster.local:4318/v1/metrics
                compression: gzip
                timeout: 10000
                headers: []
                temporality_preference: cumulative
                default_histogram_aggregation: explicit_bucket_histogram

    # Logger provider configuration
    logger_provider:
      processors:
        - simple:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otelbrot-collector.{{ .Release.Namespace }}.svc.cluster.local:4318/v1/logs
                compression: gzip
                timeout: 10000
                headers: []

      limits:
        attribute_count_limit: 128