apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-agent
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: http://otel-app-collector.{{ .Release.Namespace }}.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.13.2
    # Ensure HTTP headers are captured
    env:
      - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
        value: ".*"
      - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE  
        value: ".*"